server.port=${SERVER_PORT:8090}
spring.application.name=metrics

spring.docker.compose.enabled=false

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
spring.kafka.consumer.group-id=metrics-service-group

metrics.kafka.topic=auth_metrics

# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized

# Logging configuration
logging.level.org.apache.kafka.common.config.AbstractConfig=WARN
