spring.application.name=metrics

spring.docker.compose.enabled=false

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
spring.kafka.consumer.group-id=metrics-service-group
metrics.kafka.topic=auth.metrics

# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized
