server.port=${SERVER_PORT:8082}
spring.application.name=api

spring.docker.compose.enabled=false

# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized