server.port=${SERVER_PORT:8083}
spring.application.name=product

spring.docker.compose.enabled=false

# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized