server.port=${SERVER_PORT:8083}
spring.application.name=product

spring.docker.compose.enabled=false

# PostgreSQL
spring.datasource.url=jdbc:postgresql://${POSTGRES_PRODUCT_HOST:localhost}:${POSTGRES_PRODUCT_PORT:5433}/${POSTGRES_PRODUCT_DB:product_db}
spring.datasource.username=${POSTGRES_PRODUCT_USER:product_user}
spring.datasource.password=${POSTGRES_PRODUCT_PASSWORD:product_password_change_me}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Redis Session Stor
spring.data.redis.host=${REDIS_CATALOG_HOST:localhost}
spring.data.redis.port=${REDIS_CATALOG_PORT:6379}
spring.data.redis.password=${REDIS_CATALOG_PASSWORD:catalog_password_change_me}
spring.data.redis.timeout=2000ms

# Kafka - need to decide what metrics to send
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
auth.kafka.topic.metrics=product_metrics

# Cache - 30 days
product.category.ttl-seconds=${CATEGORY_TTL:2592000}

# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized

# Gateway Security
auth.security.gateway.enabled=true
auth.security.gateway.header-name=X-Gateway-Request
auth.security.gateway.header-value=${GATEWAY_SERVICE_SECRET:gateway-secret-change-me}
auth.security.gateway.allowed-ips=${GATEWAY_ALLOWED_IPS:gateway-service,127.0.0.1,localhost,172.18.0.0/16}

server.error.include-stacktrace=never
server.error.include-message=always