server.port=${SERVER_PORT:8088}
spring.application.name=analytics

spring.docker.compose.enabled=false

# Actuator configuration
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized